#!/usr/bin/python
# -*- coding: utf-8 -*-

#Copyright (C) 2006-2007   Néstor Arocha Rodríguez, Inmaculada Luengo Merino
#This file is part of Driza.
#
#Driza is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#Driza is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Driza; if not, write to the Free Software
#Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""Comentario para la documentación de python"""

nombre="Nombre de la operación"
tipo="Calculo" # Determina el tipo de operación. Puede ser Calculo o Casos
etiquetas=["etiqueta1", "etiqueta2"]

#Definicion widget
opcion1={
        "nombre":u"Dispersión",
        "tipo":"SeleccionMultiple",
        "opciones":["Varianza",u"Desviación",u"Máximo",u"Mínimo","Rango"]}
opcion2={
        "nombre":"Forma",
        "tipo":"SeleccionMultiple",
        "opciones":["Curtosis",u"Coeficiente de Asimetría"]}

widget={"tipo":"Variable","opciones":[opcion1, opcion2]}
# El tipo de widget permite elegir el selector

#Definicion del formato de resultados
definicionresultado = [
        {"tipo":"Tabla","nombre":"Descriptivo","autoencoger":True,"disposicion":"Vertical","cabecera":["Variable",u"Número de casos","Media","Varianza",u"Desviación","Mediana","Moda","Rango",u"Máximo",u"Mínimo","Percentil","Curtosis",u"Coeficiente de Asimetría"]}]


def funcionprincipal(dato,variable,opciones):
    from rpy import r #pylint: disable=import-error
    diccionario={"Descriptivo":{"Media":None,"Varianza":None,u"Desviación":None,"Mediana":None,"Moda":None,"Rango":None,u"Máximo":None,u"Mínimo":None,"Percentil":None,"Curtosis":None,u"Coeficiente de Asimetría":None}}
    lista=dato.query(variable)
    diccionario["Descriptivo"]["Variable"]=str(variable)
    diccionario["Descriptivo"][u"Número de casos"]=len(lista)
    if opciones.has_key("Media"): diccionario["Descriptivo"]["Media"]=r.mean(lista)
    if opciones.has_key("Varianza"): diccionario["Descriptivo"]["Varianza"]=r.var(lista)
    if opciones.has_key(u"Desviación"): diccionario["Descriptivo"][u"Desviación"]=r.sd(lista)
    if opciones.has_key("Mediana"): diccionario["Descriptivo"]["Mediana"]=r.median(lista)
    #http://cran.r-project.org/doc/contrib/Lemon-kickstart/kr_dstat.html
    #http://wiki.r-project.org/rwiki/doku.php?id=tips:stats-basic:modalvalue&s=modal
    if opciones.has_key("Moda"): diccionario["Descriptivo"]["Moda"]=__moda(lista)
    if opciones.has_key("Rango"): diccionario["Descriptivo"]["Rango"]=r.range(lista)
    if opciones.has_key(u"Máximo"): diccionario["Descriptivo"][u"Máximo"]=r.max(lista)
    if opciones.has_key(u"Mínimo"): diccionario["Descriptivo"][u"Mínimo"]=r.min(lista)
    if opciones.has_key("Percentil"): diccionario["Descriptivo"]["Percentil"]="TODO"
    if opciones.has_key("Curtosis"):
        r.require("e1071")
        diccionario["Descriptivo"]["Curtosis"]=r.kurtosis(lista)
    if opciones.has_key(u"Coeficiente de Asimetría"):
        r.require("e1071")
        diccionario["Descriptivo"][u"Coeficiente de Asimetría"]=r.skewness(lista)

    return diccionario


#Con esta funcion verificamos que las opciones que he introducido el usuario son correctas
#Para notificar un fallo, devolver False
def funcionchequeoentradausuario(opciones):  
    return True

#Con esta función verificamos que se dan las condiciones para mostrar la operación
#Para notificar un fallo, devolver False
def funcionchequeocondiciones(interfazdato):
    return True

